backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: 'static/img' # Media files will be stored in the repo under images/uploads

collections:
  - name: 'settings'
    label: 'Settings'
    editor:
      preview: false
    files:
      - name: 'metadata'
        label: 'Metadata'
        file: '_data/metadata.json'
        fields:
          - { label: 'Logo', name: 'logo', widget: 'image', required: false }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'URL', name: 'url', widget: 'string' }
          - label: 'Members'
            name: 'members'
            widget: 'list'
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Image, name: image, widget: image }
  # Our pages e.g. About
  - name: 'pages'
    label: 'Page'
    folder: 'pages'
    create: true
    editor:
      preview: false
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', default: 'New page' }
      - { label: 'Preamble', name: 'preamble', widget: 'string', required: false }
      - { label: 'File', name: 'file', widget: 'file', required: false }
      - { label: 'Permalink', name: 'permalink', widget: 'string', required: false }
      - label: 'Theme'
        name: 'theme'
        widget: 'object'
        required: false
        fields:
          - { label: 'Background Color', name: 'background_color', widget: 'string' }
          - { label: 'Text Color', name: 'text_color', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
