backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: 'static/img' # Media files will be stored in the repo under images/uploads

collections:
  - name: 'settings'
    label: 'Settings'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: 'metadata'
        label: 'Metadata'
        file: '_data/metadata.json'
        fields:
          - { label: 'Logo', name: 'logo', widget: 'image', required: false }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'URL', name: 'url', widget: 'string' }
          - label: 'Author'
            name: author
            widget: 'object'
            fields:
              - { label: 'Name', name: 'name', widget: string }
              - { label: 'Email', name: 'email', widget: string }
              - { label: 'Github', name: 'github', widget: string }
  # Our blog posts format: 'YYYY/MM/DD'
  - name: 'post' # Used in routes, e.g., /admin/collections/blog
    label: 'Post' # Used in the UI
    folder: 'posts' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string', default: 'New post' }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
  # Our pages e.g. About
  - name: 'pages'
    label: 'Page'
    folder: 'pages'
    create: false # Change to true to allow editors to create new pages
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', default: 'New page' }
      - { label: 'Permalink', name: 'permalink', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
